verbose: false
instrumentation:
    root: src
    default-excludes: true
    include-all-sources: true
    excludes: [
      'js/index.js',
      'js/routes.js',
      '**/*.test.js',
      'js/constants/*.js',
      'js/store/main.js',
      'js/reducers/index.js'
    ]
    embed-source: false
    variable: __coverage__
    compact: true
    preserve-comments: false
    complete-copy: false
    save-baseline: false
    baseline-file: ./coverage/coverage-baseline.json
reporting:
    print: summary
    reports:
        - text
        - lcov
    dir: ./coverage
    watermarks:
        statements: [50, 80]
        lines: [50, 80]
        functions: [50, 80]
        branches: [50, 80]
hooks:
    hook-run-in-context: false
    post-require-hook: null
